version: '3.8'
services:
  app:
    build: 
      context: ./backend
      dockerfile: .Dockerfile
    image: backend:dev
    container_name: app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  ui:
    build: 
      context: ./frontend
      dockerfile: .Dockerfile
    image: ui:dev
    container_name: ui
    ports:
      - "3000:3000"

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
